### ISSUE TITLE
It breaks cortex

### ISSUE THREAD

**Issue by cyberman6877** [JesseBowling/CortexIPrep#1]
Hi,

I followed your instruction and every time I add the following code (with my API key added) to my cortex application.conf, it breaks cortex and I am unable to log in to it, can you please help?

  # Analyzer configuration
  config {
    # Cortex-IPrep: this analyzer needs your API key for Packetmail.net
    CortexIPrep {
      key = "YOUR_PACKETMAIL_API_KEY"
    }

Thanks!

**Comment by JesseBowling** [comment]
Hi,

Currently this plugin only works on pre-Cortex 2 instances; it’s on the list to upgrade to support Cortex 2. I’m planning to get to that in June.

Am I correct your cortex instance is version 2.x?

Cheers,

Jesse

**Comment by cyberman6877** [comment]
Hi Jesse,

Thank you for coming back to me.  I am new to the Hive and Cortex, so I
downloaded the training VM from here:

https://github.com/TheHive-Project/TheHiveDocs/blob/master/training-material.md

The training VM includes Cerana 0.9 (TheHive 3.0.9), Cortex 2.0.4,
TheHive4py 1.4.3, Cortex4py 1.0.0 and the latest Cortex analyzers as of Apr
26, 2018.

I want to be able to test this and get it to work to demonstrate to my
boss, so appreciate if you can keep me posted on this.

Also, I am playing with your other extensions, so can I ping you if I hit
issues?

Many thanks!

Rob
Security Architect

**Comment by cyberman6877** [comment]
Hi,

Is there a work around for the plugin to work Cortex 2?  If not, what the ETA on it to be upgraded to support Cortex 2?

Many thanks!

**Comment by JesseBowling** [comment]
Hi @cyberman6877,

Finally had a chance to work on this. I've adjusted the JSON to include things needed for Cortex2, and adjust the instructions in the README.md. 

It looks that now you don't need to adjust the actual Cortex config, just drop this into your folder for custom analyzers. You then provide the analyzer config via the GUI (the API key is the only necessary config).

Let me know if this doesn't fix your issue!

**Comment by cyberman6877** [comment]
HI Jesse,

Thank you ever so much for fixing this, great to see we don't need to modify the config file anymore.  I noticed that every time I run it I get below error, I suspect this is something from my end and to do with the API key that I am using?

Invalid output
Traceback (most recent call last):
  File "CortexIPrep/cortexiprep.py", line 75, in <module>
    CortexIPrep().run()
  File "CortexIPrep/cortexiprep.py", line 61, in run
    iprep = self.search_punch(self.getData(), self.api_key)
  File "CortexIPrep/cortexiprep.py", line 43, in search_punch
    raise Exception('Remote service returned unsuccessfully:{0}'.format(repr(ret)))
Exception: Remote service returned unsuccessfully:{u'origin': u'Nathan Fowler <nathan@packetmail.net>, https://www.packetmail.net/iprep.php/', u'query_result': u'Invalid API key or temporary issue processing API key due to back-end reachability

Cheers,

cyberman6877

**Comment by JesseBowling** [comment]
Hi,

That particular message does indicate that your API key is invalid. Did you configure a valid IPRep API key in Cortex2? I also noticed that when bumping versions I had to disable the analyzer and re-enable it.

Cheers,

Jesse

> On Jun 15, 2018, at 6:17 PM, cyberman6877 <notifications@github.com> wrote:
> 
> HI Jesse,
> 
> Thank you ever so much for fixing this, great to see we don't need to modify the config file anymore. I noticed that every time I run it I get below error, I suspect this is something from my end and to do with the API key that I am using?
> 
> Invalid output
> Traceback (most recent call last):
> File "CortexIPrep/cortexiprep.py", line 75, in
> CortexIPrep().run()
> File "CortexIPrep/cortexiprep.py", line 61, in run
> iprep = self.search_punch(self.getData(), self.api_key)
> File "CortexIPrep/cortexiprep.py", line 43, in search_punch
> raise Exception('Remote service returned unsuccessfully:{0}'.format(repr(ret)))
> Exception: Remote service returned unsuccessfully:{u'origin': u'Nathan Fowler nathan@packetmail.net, https://www.packetmail.net/iprep.php/', u'query_result': u'Invalid API key or temporary issue processing API key due to back-end reachability
> 
> Cheers,
> 
> cyberman6877
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Jesse Bowling
